<?php

namespace Drupal\hear_me\Service;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Entity\RevisionableInterface;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;
use Drupal\media\Entity\Media;
use Drupal\media\MediaInterface;
use Drupal\node\NodeInterface;

/**
 * Attaches generated audio Media entities to nodes.
 *
 * @internal
 */
final class NodeAudioAttacher {

  private \Psr\Log\LoggerInterface $logger;

  public function __construct(
    private readonly ConfigFactoryInterface $configFactory,
    private readonly EntityTypeManagerInterface $entityTypeManager,
    LoggerChannelFactoryInterface $loggerFactory,
  ) {
    $this->logger = $loggerFactory->get('hear_me');
  }

  /**
   * Attaches audio Media to a node when replacement policy permits it.
   */
  public function attach(int $nid, MediaInterface $media): void {
    $config = $this->configFactory->get('hear_me.settings');
    $fieldName = $config->get('tts_audio_field') ?? 'field_tts_audio';
    $replaceGenerated = $config->get('replace_existing_generated_audio') ?? TRUE;
    $overwriteManual = $config->get('overwrite_manual_audio') ?? FALSE;
    $mediaId = (int) $media->id();
    if ($mediaId <= 0) {
      $this->logger->warning('HearMe: cannot attach unsaved audio media to node @nid.', ['@nid' => $nid]);
      return;
    }

    $node = $this->entityTypeManager->getStorage('node')->load($nid);
    if (!$node instanceof NodeInterface || !$node->hasField($fieldName)) {
      $this->logger->warning(
        'HearMe: cannot attach audio to node @nid; node not found or field "@field" does not exist.',
        ['@nid' => $nid, '@field' => $fieldName]
      );
      return;
    }

    $field = $node->get($fieldName);
    $fieldDefinition = $field->getFieldDefinition();
    $fieldStorage = $fieldDefinition->getFieldStorageDefinition();
    if ($fieldDefinition->getType() !== 'entity_reference' || $fieldStorage->getSetting('target_type') !== 'media') {
      $this->logger->warning(
        'HearMe: cannot attach audio to node @nid; field "@field" is not a media reference field.',
        ['@nid' => $nid, '@field' => $fieldName]
      );
      return;
    }

    if ($this->getFieldTargetIds($field->getValue()) === [$mediaId]) {
      return;
    }

    if (!$field->isEmpty()) {
      $existingMediaIds = $this->getFieldTargetIds($field->getValue());
      $existingIsGenerated = $this->allMediaIdsAreHearMeGenerated($existingMediaIds);

      if ($existingIsGenerated && !$replaceGenerated) {
        $this->logger->notice(
          'HearMe: skipped replacing generated audio on node @nid because replacement of existing generated audio is disabled for field "@field".',
          ['@nid' => $nid, '@field' => $fieldName]
        );
        return;
      }

      if (!$existingIsGenerated && !$overwriteManual) {
        $this->logger->notice(
          'HearMe: skipped replacing audio on node @nid because field "@field" contains manually selected or unknown audio and manual overwrite is disabled.',
          ['@nid' => $nid, '@field' => $fieldName]
        );
        return;
      }
    }

    $node->set($fieldName, ['target_id' => $mediaId]);
    $violations = $node->get($fieldName)->validate();
    if ($violations->count() > 0) {
      $this->logger->error(
        'HearMe: skipped attaching audio to node @nid because field "@field" failed validation: @violations',
        [
          '@nid' => $nid,
          '@field' => $fieldName,
          '@violations' => $this->summarizeViolations($violations),
        ]
      );
      return;
    }

    if ($node instanceof RevisionableInterface) {
      $node->setNewRevision(FALSE);
    }
    $node->save();
  }

  /**
   * Returns a compact validation violation summary for logs.
   */
  private function summarizeViolations(\Traversable $violations): string {
    $messages = [];
    foreach ($violations as $violation) {
      $messages[] = trim($violation->getPropertyPath() . ': ' . $violation->getMessage());
    }

    return implode('; ', $messages);
  }

  /**
   * Extracts referenced entity IDs from an entity reference field value array.
   */
  private function getFieldTargetIds(array $fieldValues): array {
    $targetIds = [];
    foreach ($fieldValues as $fieldValue) {
      $targetId = (int) ($fieldValue['target_id'] ?? 0);
      if ($targetId > 0) {
        $targetIds[] = $targetId;
      }
    }

    return array_values(array_unique($targetIds));
  }

  /**
   * Checks whether all referenced media appear to be generated by HearMe.
   */
  private function allMediaIdsAreHearMeGenerated(array $mediaIds): bool {
    if (!$mediaIds) {
      return FALSE;
    }

    $mediaStorage = $this->entityTypeManager->getStorage('media');
    foreach ($mediaIds as $mediaId) {
      $media = $mediaStorage->load($mediaId);
      if (!$media instanceof Media || !$this->isHearMeGeneratedMedia($media)) {
        return FALSE;
      }
    }

    return TRUE;
  }

  /**
   * Checks whether a media entity appears to contain HearMe-generated audio.
   */
  private function isHearMeGeneratedMedia(Media $media): bool {
    if ($media->bundle() !== 'hear_me_audio' || !$media->hasField('field_hear_me_audio_file') || $media->get('field_hear_me_audio_file')->isEmpty()) {
      return FALSE;
    }

    $fileStorage = $this->entityTypeManager->getStorage('file');
    foreach ($media->get('field_hear_me_audio_file')->getValue() as $fileValue) {
      $file = $fileStorage->load((int) ($fileValue['target_id'] ?? 0));
      if (!$file || !str_starts_with((string) $file->getFileUri(), TtsCacheManager::RUNTIME_PUBLIC_URI_BASE)) {
        return FALSE;
      }
    }

    return TRUE;
  }

}
